theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-dark.svg"